#!/bin/bash
#BSUB -P CSC276
#BSUB -W 8:00
#BSUB -nnodes 512 
#BSUB -J hypervgg512
#BSUB -o out.%J
#BSUB -e err.%J

export PATH="/gpfs/alpinetds/proj-shared/csc276/yngtodd/anaconda3/bin:$PATH"

#BSEC Module
BSECMODULEDIR=/gpfs/alpinetds/csc276/proj-shared/modules
[[ -d $BSECMODULEDIR/modulefiles ]] && module use $BSECMODULEDIR/modulefiles

module load pytorch 

cd /gpfs/alpinetds/proj-shared/csc276/yngtodd/paper_hyperspace/vgg/fivetwelve 

date
jsrun -n 512 -a 1 -g 6 python hyper512.py --results_dir /gpfs/alpinetds/proj-shared/csc276/yngtodd/paper_hyperspace/vgg/fivetwelve/results
